/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE OS CLIENTES QUE POSSUEM ALGUMA NOTA FISCAL CADASTRADA, ORDENADOS POR CÓDIGO DO CLINTE
E DATA DA EMISSÃO DA NOTA FISCAL (CRESCENTE).
MOSTRE O CÓDIGO DO CLIENTE E DATA DA EMISSÃO DA NOTA FISCAL SEM REPETIÇÃO.
*/
SELECT DISTINCT
  CD_CLIENTE,
  DT_EMISSAO
FROM
  T_SPV_NOTA_FISCAL
ORDER BY CD_CLIENTE, DT_EMISSAO;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS PERTENCENTES AO CLIENTE "JOÃO DA SILVA" (CÓDIGO DO CLIENTE = 3),
EMITIDAS A PARTIR DE 18/08/2014, ORDENADOS POR DATA DA EMISSÃO (CRESCENTE).
MOSTRE O CÓDIGO DO CLIENTE, NÚMERO DA NOTA FISCAL, DATA DA EMISSÃO E VALOR TOTAL DA NOTA
FISCAL.
OBSERVAÇÃO: UTILIZAR A FUNÇÃO TO_DATE(<DATA>,<FORMATO>) PARA FORMATAR A DATA NO MOMENTO
DA CONSULTA.
OBS.: ALTERADO PARA DIA 15/08/2014 POIS NÃO HAVIA NOTA A PARTIR DO DIA 18.
*/
SELECT
  CD_CLIENTE,
  NR_NOTA_FISCAL,
  DT_EMISSAO,
  VL_TOTAL_NF
FROM
  T_SPV_NOTA_FISCAL
WHERE
  CD_CLIENTE = 3 AND
  DT_EMISSAO >= TO_DATE('15/08/2014', 'DD/MM/YYYY')
ORDER BY DT_EMISSAO;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS EMITIDAS ENTRE ‘15/08/2014’ E ‘31/08/2014’, QUE NÃO TENHAM UM
DESCONTO CONCEDIDO.
MOSTRE O NÚMERO DA NOTA FISCAL, DATA DE EMISSÃO, VALOR TOTAL DA NOTA FISCAL E O VALOR DO
PERCENTUAL DE DESCONTO.
OBSERVAÇÃO:
 UTILIZAR A FUNÇÃO TO_DATE(<DATA>,<FORMATO>) PARA FORMATAR A DATA NO MOMENTO DA
CONSULTA.
 UTILIZAR O OPERADOR ESPECIAL BETWEEN PARA A CONDIÇÃO DE DATA DE EMISSÃO.
*/
SELECT
  NR_NOTA_FISCAL,
  DT_EMISSAO,
  VL_TOTAL_NF,
  VL_DESCONTO
FROM
  T_SPV_NOTA_FISCAL
WHERE
  DT_EMISSAO BETWEEN TO_DATE('15/08/2014','DD/MM/YYYY') AND
                     TO_DATE('31/08/2014','DD/MM/YYYY') AND
  VL_DESCONTO IS NULL;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS QUE POSSUEM O TIPO DE NOTA FISCAL IGUAL A 2 OU QUE TENHAM UM
DESCONTO CONCEDIDO.
MOSTRE O NÚMERO DA NOTA FISCAL, DATA DE EMISSÃO, TIPO DE NOTA FISCAL, VALOR TOTAL DA NOTA
FISCAL E O VALOR DO PERCENTUAL DE DESCONTO.
*/
SELECT
  NR_NOTA_FISCAL,
  DT_EMISSAO,
  DS_TIPO,
  VL_TOTAL_NF,
  VL_DESCONTO
FROM
  T_SPV_NOTA_FISCAL
WHERE
  DS_TIPO = 2 OR 
  VL_DESCONTO IS NOT NULL;
  
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS EMITIDAS NO ANO DE 2014, QUE POSSUEM VALOR TOTAL DA NOTA FISCAL
SUPERIOR A 500.00.
MOSTRE O NÚMERO DA NOTA FISCAL, DATA DE EMISSÃO, VALOR TOTAL DA NOTA FISCAL, VALOR DO
PERCENTUAL DE DESCONTO E O RESULTADO DO CÁLCULO DO VALOR DO DESCONTO.
O RESULTADO DEVERÁ VIR ORDENADO PELO VALOR DO DESCONTO CALCULADO (DECRESCENTE).
CRIE UM ALIAS PARA AS COLUNAS:
 NÚMERO DA NOTA FISCAL ("NR. NOTA FISCAL")
 DATA DA EMISSÃO ("DATA EMISSÃO")
 VALOR TOTAL DA NOTA FISCAL ("VL. TOTAL NF")
 VALOR DO PERCENTUAL DE DESCONTO ("% DESCONTO")
 CÁLCULO DO VALOR DO DESCONTO ("VALOR DO DESCONTO")
OBSERVAÇÃO:
 UTILIZAR A FUNÇÃO TO_CHAR(<CONTEUDO>,<FORMATO>) PARA FORMATAR A DATA (ANO) NO
MOMENTO DA CONSULTA.
 CÁLCULO REFERENTE AO VALOR DO DESCONTO: (VALOR TOTAL DA NOTA FISCAL * (VALOR DO
DESCONTO/100))  
*/
SELECT
  NR_NOTA_FISCAL AS "NR. NOTA FISCAL",
  DT_EMISSAO AS "DATA EMISSÃO",
  VL_TOTAL_NF AS "VL. TOTAL NF",
  VL_DESCONTO AS "% DESCONTO",
  ((VL_TOTAL_NF * VL_DESCONTO) / 100) AS "VALOR DO DESCONTO"
FROM
  T_SPV_NOTA_FISCAL
WHERE
  TO_CHAR(DT_EMISSAO, 'YYYY') = '2014' AND
  VL_TOTAL_NF > 500.00
ORDER BY "VALOR DO DESCONTO" DESC;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS CLASSIFICADAS POR:
 DATA DE EMISSÃO (DECRESCENTE)
 CÓDIGO DO CLIENTE (CRESCENTE)
 NÚMERO DA NOTA FISCAL (CRESCENTE)
MOSTRE A DATDATA DE EMISSÃO, CÓDIGO DO CLIENTE, NÚMERO DA NOTA FISCAL E O VALOR TOTAL DA NOTA
FISCAL.
*/
SELECT
  DT_EMISSAO,
  CD_CLIENTE,
  NR_NOTA_FISCAL,
  VL_TOTAL_NF
FROM
  T_SPV_NOTA_FISCAL
ORDER BY DT_EMISSAO DESC, CD_CLIENTE ASC, NR_NOTA_FISCAL ASC;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA ITEM NOTA FISCAL.
LISTE OS ITENS DA NOTA FISCAL DE NÚMERO: 1235.
MOSTRE O NÚMERO DA NOTA FISCAL, CÓDIGO DO ITEM, CÓDIGO DO PRODUTO, QUANTIDADE VENDIDA,
PREÇO UNITÁRIO E O RESULTADO DO CÁLCULO DO VALOR DE CADA ITEM.
CRIE UM ALIAS PARA AS COLUNAS:
 NÚMERO DA NOTA FISCAL ("NR. NOTA FISCAL")
 CÓDIGO DO ITEM ("ITEM")
 CÓDIGO DO PRODUTO ("COD. PRODUTO")
 QUANTIDADE VENDIDA ("QTDE. VENDIDA")
 PREÇO UNITÁRIO ("PREÇO UNIT.")
 CÁLCULO DO VALOR DE CADA ITEM ("VALOR DO ITEM")
OBSERVAÇÃO:
 CÁLCULO REFERENTE AO VALOR DO DESCONTO: (QUANTIDADE VENDIDA * VALOR UNITÁRIO)
*/
SELECT 
  NR_NOTA_FISCAL AS "NR. NOTA FISCAL",
  CD_ITEM AS ITEM,
  CD_PRODUTO AS "COD. PRODUTO",
  QT_VENDIDA AS "QTDE. VENDIDA",
  VL_PRECO_UNITARIO AS "PREÇO UNIT.",
  (QT_VENDIDA * VL_PRECO_UNITARIO) AS "VALOR DO ITEM"
FROM
  T_SPV_ITEM_NOTA_FISCAL
WHERE 
  NR_NOTA_FISCAL = 1235;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS EMITIDAS NO ANO DE 2013 OU 2014 E QUE POSSUEM VALOR TOTAL DA NOTA
FISCAL INFERIOR A 600.00 OU QUE SEJAM DO TIPO DE NOTA FISCAL IGUAL A 1.
MOSTRE O NÚMERO DA NOTA FISCAL, DATA DE EMISSÃO, TIPO DE NOTA FISCAL, VALOR TOTAL DA NOTA
FISCAL, VALOR DO PERCENTUAL DE DESCONTO.
OBSERVAÇÃO:
 UTILIZAR A FUNÇÃO TO_CHAR(<CONTEUDO>,<FORMATO>) PARA FORMATAR A DATA (ANO) NO
MOMENTO DA CONSULTA.
 UTILIZAR O OPERADOR ESPECIAL IN() PARA A CONDIÇÃO DE DATA (ANO).
 UTILIZAR APELIDO DE TABELAS (ALIAS: "NF") E O QUALIFICADOR (IDENTIFICADOR DE TABELAS).
*/
SELECT
  NR_NOTA_FISCAL,
  DT_EMISSAO,
  CD_CLASSIFICACAO_FISCAL,
  VL_TOTAL_NF,
  VL_DESCONTO
FROM
  T_SPV_NOTA_FISCAL
WHERE
  TO_CHAR(DT_EMISSAO, 'YYYY') IN (2013, 2014) AND
  VL_TOTAL_NF > 600.00 AND
  CD_CLASSIFICACAO_FISCAL = 1;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODAS AS NOTAS FISCAIS EMITIDAS NOS DIAS DA SEMANA (6=SEXTA-FEIRA E 7=SÁBADO).
MOSTRE O NÚMERO DA NOTA FISCAL, DATA DE EMISSÃO, TIPO DE NOTA FISCAL, VALOR TOTAL DA NOTA
FISCAL.
CRIE UM ALIAS PARA AS COLUNAS:
 NÚMERO DA NOTA FISCAL ("NR. NOTA FISCAL")
 DATA DA EMISSÃO ("DATA EMISSÃO")
 DESCRIÇÃO DO TIPO DE NOTA FISCAL ("TIPO NF")
 VALOR TOTAL DA NOTA FISCAL ("VL. TOTAL NF")
OBSERVAÇÃO:
 UTILIZAR A FUNÇÃO TO_CHAR(<CONTEUDO>,<FORMATO>) PARA FORMATAR A DATA (DIA) NO
MOMENTO DA CONSULTA.(O FORMATO NESTE CASO SERÁ "D" - DIA.
 UTILIZAR O OPERADOR ESPECIAL IN() PARA A CONDIÇÃO DE DATA (DIA).
 UTILIZAR APELIDO DE TABELAS (ALIAS: "NF") E O QUALIFICADOR (IDENTIFICADOR DE TABELAS).
*/
SELECT
  NF.NR_NOTA_FISCAL AS "NR. NOTA FISCAL",
  NF.DT_EMISSAO AS "DATA EMISSÃO",
  NF.DS_TIPO AS "TIPO NF",
  NF.VL_TOTAL_NF AS "VL. TOTAL NF"
FROM
  T_SPV_NOTA_FISCAL NF
WHERE
  TO_CHAR(NF.DT_EMISSAO, 'D') IN (6,7);
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA PRODUTO.
LISTE TODOS OS PRODUTOS EM ESTOQUE.
MOSTRE O CÓDIGO DO PRODUTO, DESCRIÇÃO DO PRODUTO, QUANTIDADE EM ESTOQUE, PREÇO UNITÁRIO
DE CADA PRODUTO E O RESULTADO DO CÁLCULO DO VALOR EM ESTOQUE.
O RESULTADO DEVERÁ VIR ORDENADO PELO VALOR EM ESTOQUE CALCULADO (DECRESCENTE).
CRIE UM ALIAS PARA AS COLUNAS:
 PREÇO UNITÁRIO ("PREÇO UNIT.")
 CÁLCULO DO VALOR EM ESTOQUE ("VALOR EM ESTOQUE")
OBSERVAÇÃO:
 CÁLCULO REFERENTE AO VALOR EM ESTOQUE: (QUANTIDADE EM ESTOQUE * PREÇO UNITÁRIO)
*/
SELECT 
 CD_PRODUTO,
 DS_PRODUTO,
 QT_ESTOQUE,
 VL_PRECO_UNITARIO AS "PREÇO UNIT.",
 (QT_ESTOQUE * VL_PRECO_UNITARIO) AS "VALOR EM ESTOQUE"
FROM
  T_SPV_PRODUTO;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA PRODUTO.
LISTE TODOS OS PRODUTOS EM ESTOQUE.
MOSTRE UMA MENSAGEM CONTENDO O SEGUINTE TEXTO:
"O PRODUTO (<CÓDIGO DO PRODUTO> - <DESCRIÇÃO DO PRODUTO>) POSSUI <QUANTIDADE EM ESTOQUE>
UNIDADES EM ESTOQUE".
O RESULTADO DEVERÁ VIR ORDENADO PELA QUANTIDADE EM ESTOQUE (DECRESCENTE).
CRIE UM ALIAS PARA A MENSAGEM ("ESTOQUE DE PRODUTOS")
OBSERVAÇÃO:
 UTILIZAR O OPERADOR PARA CONCATENAÇÃO "||".
*/
SELECT 
 'O PRODUTO ' || CD_PRODUTO || ' - ' || DS_PRODUTO || ') POSSUI '|| QT_ESTOQUE ||' UNIDADES EM ESTOQUE' AS "ESTOQUE DE PRODUTOS"
FROM
  T_SPV_PRODUTO
ORDER BY QT_ESTOQUE DESC;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NA TABELA NOTA FISCAL.
LISTE TODOS AS NOTAS FISCAIS, CALCULANDO O TEMPO QUE CADA UMA FOI EMITIDA.
MOSTRE UMA MENSAGEM CONTENDO O SEGUINTE TEXTO:
"A NOTA FISCAL FOI EMITIDA HÁ ( <CÁLCULO DO TEMPO EM QUE FORAM EMITIDAS> ) DIAS."
O RESULTADO DEVERÁ VIR ORDENADO PELO TEMPO QUE FORAM EMITIDAS (DECRESCENTE).
CRIE UM ALIAS PARA A MENSAGEM ("TEMPO EMISSÃO").
OBSERVAÇÃO:
 UTILIZAR O OPERADOR PARA CONCATENAÇÃO "||".
 UTILIZAR A FUNÇÃO TO_CHAR(<CONTEUDO>) PARA FORMATAR A DATA NO MOMENTO DA
CONSULTA.
 CÁLCULO REFERENTE AO CÁLCULO DO TEMPO QUE UMA NOTA FISCAL FOI EMITIDA (SYSDATE - DATA
DA EMISSÃO).
*/
SELECT
  'A NOTA FISCAL FOI EMITIDA HÁ ( '|| (SYSDATE - DT_EMISSAO) ||') DIAS.' AS "TEMPO EMISSÃO"
FROM
T_SPV_NOTA_FISCAL
ORDER BY DT_EMISSAO ASC;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS PRODUTO E UNIDADE DE
MEDIDA.
LISTE TODOS OS PRODUTOS ASSOCIADOS À UNIDADE DE MEDIDA QUE TENHA NA SEGUNDA LETRA DO NOME
A LETRA "A".
MOSTRE O CÓDIGO DO PRODUTO, DESCRIÇÃO DO PRODUTO E CÓDIGO DA UNIDADE DE MEDIDA.
OBSERVAÇÃO:
 UTILIZAR O OPERADOR ESPECIAL LIKE.
 UTILIZAR A FUNÇÃO UPPER() NA COMPARAÇÃO DA DESCRIÇÃO DA UNIDADE DE MEDIDA
 UTILIZAR SUBCONSULTA.
14.)
OBS.: NÃO HAVIA NENHUM PRODUTO COM A SEGUNDA LETRA A, POR ISSO, TROQUEI PARA O
*/
SELECT
  P.CD_PRODUTO,
  P.DS_PRODUTO,
  U.CD_UNIDADE_MEDIDA
FROM
  T_SPV_PRODUTO P,
  T_SPV_UNIDADE_MEDIDA U
WHERE
  P.CD_UNIDADE_MEDIDA = U.CD_UNIDADE_MEDIDA AND
  UPPER(P.DS_PRODUTO) LIKE '_O%';
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS PRODUTO E ITEM NOTA
FISCAL.
LISTE O ITEM DA NOTA FISCAL QUE ESTEJA ASSOCIADO AO PRODUTO DE CÓDIGO IGUAL A 6.
MOSTRE O NÚMERO DA NOTA FISCAL, CÓDIGO DO ITEM, CÓDIGO DO PRODUTO, QUANTIDADE VENDIDA E
PREÇO UNITÁRIO.
O PREÇO UNITÁRIO DEVERÁ SER RECUPERADO DA TABELA PRODUTO, ATRAVÉS DE UMA SUBCONSULTA.
CRIE UM ALIAS PARA O PREÇO UNITÁRIO RETORNADO DA TABELA PRODUTO ("PREÇO UNIT. (PRODUTO)").
OBSERVAÇÃO:
 UTILIZAR SUBCONSULTA.
*/
SELECT
  NR_NOTA_FISCAL,
  CD_ITEM,
  CD_PRODUTO,
  QT_VENDIDA,
  VL_PRECO_UNITARIO AS "PREÇO UNIT. (PRODUTO)"
FROM
  T_SPV_ITEM_NOTA_FISCAL
WHERE
  CD_PRODUTO = (SELECT CD_PRODUTO FROM T_SPV_PRODUTO WHERE CD_PRODUTO = 6);

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS PRODUTO E ITEM NOTA FISCAL.
A PARTIR DA SOLICITAÇÃO DO EXERCÍCIO ANTERIOR, CRIE UMA CONSULTA QUE LISTE TODOS OS ITENS DA NOTA FISCAL.
MOSTRE O NÚMERO DA NOTA FISCAL, CÓDIGO DO ITEM, CÓDIGO DO PRODUTO, QUANTIDADE VENDIDA E PREÇO UNITÁRIO.
O PREÇO UNITÁRIO DEVERÁ SER RECUPERADO DA TABELA PRODUTO, ATRAVÉS DE UMA SUBCONSULTA.
CRIE UM ALIAS PARA O PREÇO UNITÁRIO RETORNADO DA TABELA PRODUTO ("PREÇO UNIT. (PRODUTO)").
OBSERVAÇÃO:
 UTILIZAR APELIDO DE TABELAS (ALIAS: "ITEM") E O QUALIFICADOR (IDENTIFICADOR DE TABELAS) PARA A TABELA ITEM DA NOTA FISCAL.
 UTILIZAR SUBCONSULTA.
*/

SELECT
  ITEM.NR_NOTA_FISCAL,
  ITEM.CD_ITEM,
  ITEM.CD_PRODUTO,
  ITEM.QT_VENDIDA,
  (SELECT VL_PRECO_UNITARIO FROM T_SPV_PRODUTO WHERE CD_PRODUTO = ITEM.CD_PRODUTO) AS "PREÇO UNIT. (PRODUTO)"
FROM
  T_SPV_ITEM_NOTA_FISCAL ITEM;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS PRODUTO E UNIDADE DE MEDIDA.
LISTE TODOS OS PRODUTOS CADASTRADOS.
MOSTRE O CÓDIGO DO PRODUTO, SIGLA E DESCRIÇÃO DA UNIDADE DE MEDIDA E A DESCRIÇÃO DO PRODUTO.
A SIGLA E A DESCRIÇÃO DEVEM SER RECUPERADAS DA TABELA UNIDADE DE MEDIDA, ATRAVÉS DE UMA SUBCONSULTA.
A SIGLA E A DESCRIÇÃO DEVEM SER RETORNADAS CONFORME TEXTO: "( <SIGLA> ) - <DESCRIÇÃO DA UNIDADE DE MEDIDA>".
CRIE UM ALIAS PARA A SIGLA E DESCRIÇÃO DA UNIDADE DE MEDIDA ("UNIDADE DE MEDIDA").
OBSERVAÇÃO:
 UTILIZAR APELIDO DE TABELAS (ALIAS: "PROD") E O QUALIFICADOR (IDENTIFICADOR DE TABELAS) PARA A TABELA PRODUTO.
 UTILIZAR SUBCONSULTA.
 UTILIZAR O OPERADOR PARA CONCATENAÇÃO "||".
*/
SELECT 
  PROD.CD_PRODUTO,
  '( '|| U.DS_SIGLA ||' ) - '|| U.DS_UNIDADE_MEDIDA AS "UNIDADE DE MEDIDA",
  PROD.DS_PRODUTO
FROM
  T_SPV_PRODUTO PROD,
  T_SPV_UNIDADE_MEDIDA U
WHERE
  PROD.CD_UNIDADE_MEDIDA = U.CD_UNIDADE_MEDIDA;

/*
  UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS NOTA FISCAL E CLIENTE.
LISTE AS NOTAS FISCAIS QUE NÃO PERTENÇAM A CLIENTES QUE POSSUEM "ANA" EM ALGUMA PARTE DO
NOME.
MOSTRE O NÚMERO DA NOTA FISCAL, CÓDIGO DO CLIENTE E O VALOR TOTAL DA NOTA FISCAL.
OBSERVAÇÃO:
 UTILIZAR SUBCONSULTA.
 UTILIZAR O OPERADOR ESPECIAL LIKE.
 UTILIZAR O OPERADOR ESPECIAL NOT IN.
 UTILIZAR A FUNÇÃO UPPER() NA COMPARAÇÃO DA DESCRIÇÃO DO NOME DE CLIENTE.
*/
  
SELECT
  NR_NOTA_FISCAL,
  CD_CLIENTE,
  VL_TOTAL_NF
FROM
  T_SPV_NOTA_FISCAL
WHERE
  CD_CLIENTE NOT IN (SELECT CD_CLIENTE FROM T_SPV_CLIENTE WHERE UPPER(NM_CLIENTE) LIKE '%ANA%');
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS NOTA FISCAL E CLIENTE.
A PARTIR DA SOLICITAÇÃO DO EXERCÍCIO ANTERIOR, CRIE UMA CONSULTA QUE LISTE AS NOTAS FISCAIS QUE
PERTENÇAM A CLIENTES QUE POSSUEM "ANA" EM ALGUMA PARTE DO NOME.
MOSTRE O NÚMERO DA NOTA FISCAL, NOME DO CLIENTE E O VALOR TOTAL DA NOTA FISCAL.
O NOME DO CLIENTE DEVE SER RECUPERADO DA TABELA CLIENTE, O NOME DO CLIENTE ("NOME DO
CLIENTE").
OBSERVAÇÃO:
 UTILIZAR SUBCONSULTA.
 UTILIZAR O OPERADOR ESPECIAL LIKE.
 UTILIZAR O OPERADOR ESPECIAL IN.
 UTILIZAR A FUNÇÃO UPPER() NA COMPARAÇÃO DA DESCRIÇÃO DO NOME DE CLIENTE.
*/
SELECT
  NR_NOTA_FISCAL,
  CD_CLIENTE,
  VL_TOTAL_NF
FROM
  T_SPV_NOTA_FISCAL
WHERE
  CD_CLIENTE IN (SELECT CD_CLIENTE FROM T_SPV_CLIENTE WHERE UPPER(NM_CLIENTE) LIKE '%ANA%');
  
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS NOTA FISCAL E CLIENTE.
A PARTIR DA SOLICITAÇÃO DO EXERCÍCIO ANTERIOR, CRIE UMA CONSULTA QUE LISTE AS NOTAS FISCAIS QUE
NÃO PERTENÇAM A CLIENTES QUE POSSUEM "ANA" EM ALGUMA PARTE DO NOME.
MOSTRE O NÚMERO DA NOTA FISCAL, NOME DO CLIENTE E O VALOR TOTAL DA NOTA FISCAL.
O NOME DO CLIENTE DEVE SER RECUPERADO DA TABELA CLIENTE, O NOME DO CLIENTE ("NOME DO
CLIENTE").
OBSERVAÇÃO:
 UTILIZAR SUBCONSULTA.
 UTILIZAR O OPERADOR ESPECIAL LIKE.
 UTILIZAR O OPERADOR ESPECIAL NOT IN.
 UTILIZAR A FUNÇÃO UPPER() NA COMPARAÇÃO DA DESCRIÇÃO DO NOME DE CLIENTE.
*/
SELECT
  NR_NOTA_FISCAL,
  CD_CLIENTE,
  VL_TOTAL_NF,
  (SELECT NM_CLIENTE FROM T_SPV_CLIENTE WHERE CD_CLIENTE = T_SPV_NOTA_FISCAL.CD_CLIENTE) AS "NOME CLIENTE"
FROM
  T_SPV_NOTA_FISCAL
WHERE
  CD_CLIENTE NOT IN (SELECT CD_CLIENTE FROM T_SPV_CLIENTE WHERE UPPER(NM_CLIENTE) LIKE '%ANA%');
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS NOTA FISCAL E CLIENTE.
A PARTIR DA SOLICITAÇÃO DO EXERCÍCIO 15, ACRESCENTE A CONSULTA A EXIBIÇÃO DA PSEUDOCOLUNA
ROWNUM.
SOLICITAÇÃO EXERCÍCIO 15 - CRIE UMA CONSULTA QUE LISTE TODOS OS ITENS DA NOTA FISCAL APENAS DOS
ITENS CUJA QUANTIDADE VENDIDA SEJA IGUAL A 1.
MOSTRE A PSEUDOCOLUNA ROWNUM, O NÚMERO DA NOTA FISCAL, CÓDIGO DO ITEM, CÓDIGO DO
PRODUTO, QUANTIDADE VENDIDA E PREÇO UNITÁRIO.
O PREÇO UNITÁRIO DEVERÁ SER RECUPERADO DA TABELA PRODUTO, ATRAVÉS DE UMA SUBCONSULTA.
CRIE UM ALIAS PARA O PREÇO UNITÁRIO RETORNADO DA TABELA PRODUTO ("PREÇO UNIT. (PRODUTO)").
RESTRINJA A QUANTIDADE DE LINHAS RECUPERADAS EM 4 LINHAS.
OBSERVAÇÃO:
 UTILIZAR APELIDO DE TABELAS (ALIAS: "ITEM") E O QUALIFICADOR (IDENTIFICADOR DE TABELAS)
PARA A TABELA ITEM DA NOTA FISCAL.
 UTILIZAR SUBCONSULTA.
 UTILIZAR A PSEUDOCOLUNA ROWNUM.
*/

SELECT
  ROWNUM,
  ITEM.NR_NOTA_FISCAL,
  ITEM.CD_ITEM,
  ITEM.CD_PRODUTO,
  ITEM.QT_VENDIDA,
  (SELECT VL_PRECO_UNITARIO FROM T_SPV_PRODUTO WHERE CD_PRODUTO = ITEM.CD_PRODUTO) AS "PREÇO UNIT. (PRODUTO)"
FROM
  T_SPV_ITEM_NOTA_FISCAL ITEM
WHERE 
  ROWNUM <= 4;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS NOTA FISCAL E CLIENTE.
(DESAFIO) LISTE AS 3 NOTAS FISCAIS DE MAIOR VALOR.
MOSTRE O RANK, NÚMERO DA NOTA FISCAL, NOME DO CLIENTE E VALOR TOTAL DA NOTA FISCAL.
O NOME DO CLIENTE DEVERÁ SER RECUPERADO DA TABELA CLIENTE, ATRAVÉS DE UMA SUBCONSULTA.
CRIE UM ALIAS PARA O NOME DO CLIENTE RETORNADO DA TABELA CLIENTE ("NOME CLIENTE").
CRIE UM ALIAS PARA AS COLUNAS:
 ROWNUM ("RANK")
 NÚMERO DA NOTA FISCAL ("NR. NOTA FISCAL")
 VALOR TOTAL DA NOTA FISCAL (VALOR TOTAL)
OBSERVAÇÃO:
 UTILIZAR APELIDO DE TABELAS (ALIAS: "NF") E O QUALIFICADOR (IDENTIFICADOR DE TABELAS) PARA A
TABELA NOTA FISCAL.
 UTILIZAR SUBCONSULTA.
 UTILIZAR A PSEUDOCOLUNA ROWNUM.
 UTILIZAR O CONCEITO DE ANÁLISE TOP-N.
*/
SELECT
  ROWNUM AS RANK,
  NF.NR_NOTA_FISCAL AS "NR. NOTA FISCAL", 
  (SELECT NM_CLIENTE FROM T_SPV_CLIENTE WHERE CD_CLIENTE = NF.CD_CLIENTE) AS "NOME CLIENTE",
  NF.VL_TOTAL_NF AS "VALOR TOTAL"
FROM
  T_SPV_NOTA_FISCAL NF
WHERE
  ROWNUM < 4
ORDER BY NF.VL_TOTAL_NF DESC;