/*
DROP TABLE T_AUTOR CASCADE CONSTRAINTS ;

DROP TABLE T_AUTOR_LIVRO CASCADE CONSTRAINTS ;

DROP TABLE T_CATEGORIA CASCADE CONSTRAINTS ;

DROP TABLE T_LIVRO CASCADE CONSTRAINTS ;
*/

CREATE TABLE T_AUTOR
  (
    cd_autor               NUMBER (3) NOT NULL ,
    nm_primeiro_nome_autor VARCHAR2 (20) NOT NULL ,
    nm_segundo_nome_autor  VARCHAR2 (40) NOT NULL ,
    nm_nome_completo       VARCHAR2 (40) NOT NULL ,
    ds_email               VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE T_AUTOR ADD CONSTRAINT PK_AUTOR PRIMARY KEY ( cd_autor ) ;
ALTER TABLE T_AUTOR ADD CONSTRAINT UN_AUTOR_EMAIL UNIQUE ( ds_email ) ;

CREATE TABLE T_AUTOR_LIVRO
  (
    cd_autor           NUMBER (3) NOT NULL ,
    nr_isbn            NUMBER (8) NOT NULL ,
    st_autor_principal NUMBER (1) NOT NULL
  ) ;
ALTER TABLE T_AUTOR_LIVRO ADD CONSTRAINT CK_AULA_AUTOR_LIVRO_STAT CHECK (st_autor_principal IN(1,2)) ;
ALTER TABLE T_AUTOR_LIVRO ADD CONSTRAINT PK_AUTOR_LIVRO PRIMARY KEY ( nr_isbn, cd_autor ) ;

CREATE TABLE T_CATEGORIA
  (
    cd_categoria   NUMBER (3) NOT NULL ,
    ds_sigla_categ CHAR (3) NOT NULL ,
    ds_categoria   VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE T_CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY ( cd_categoria ) ;
ALTER TABLE T_CATEGORIA ADD CONSTRAINT UN_CATEGORIA_CATEGORIA UNIQUE ( ds_categoria ) ;
ALTER TABLE T_CATEGORIA ADD CONSTRAINT UN_CATEGORIA_SIGLA UNIQUE ( ds_sigla_categ ) ;

CREATE TABLE T_LIVRO
  (
    nr_isbn      NUMBER (8) NOT NULL ,
    cd_categoria NUMBER (3) NOT NULL ,
    nm_titulo    VARCHAR2 (50) NOT NULL ,
    ds_sinopse   VARCHAR2 (200) NOT NULL ,
    nr_edicao    NUMBER (2) NOT NULL ,
    nr_ano       NUMBER (4) NOT NULL
  ) ;
ALTER TABLE T_LIVRO ADD CONSTRAINT CK_AULA_LIVRO_EDICAO CHECK (nr_edicao>0) ;
ALTER TABLE T_LIVRO ADD CONSTRAINT CK_AULA_LIVRO_ANO CHECK (nr_ano      >0) ;
ALTER TABLE T_LIVRO ADD CONSTRAINT PK_LIVRO PRIMARY KEY ( nr_isbn ) ;

ALTER TABLE T_AUTOR_LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO FOREIGN KEY ( cd_autor ) REFERENCES T_AUTOR ( cd_autor ) ;

ALTER TABLE T_LIVRO ADD CONSTRAINT FK_CATEG_LIVRO FOREIGN KEY ( cd_categoria ) REFERENCES T_CATEGORIA ( cd_categoria ) ;

ALTER TABLE T_AUTOR_LIVRO ADD CONSTRAINT FK_LIVRO_AUTOR FOREIGN KEY ( nr_isbn ) REFERENCES T_LIVRO ( nr_isbn ) ;

