-- EXEMPLO DE SEQUENCIA

------------------------------------------------------
-- Criando sequencias para geração de autonumericos --
------------------------------------------------------
-- Sequencia tabela AUTOR
CREATE SEQUENCE SQ_AUTOR
INCREMENT BY 1
START WITH 1
MAXVALUE 999
NOCACHE
NOCYCLE;
--
-- DROP SEQUENCE SQ_AUTOR;


-- CONSULTA A TABELA USER_SEQUENCES
SELECT SEQUENCE_NAME, 
       INCREMENT_BY, 
       MAX_VALUE, 
       LAST_NUMBER 
  FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME='SQ_AUTOR';


-- DESC = DESCRIBE -> RETORNA A DESCRIÇÃO DA TABELA
-- MOSTRA A ESTRUTURA DA TABELA ESPECIFICADA
Desc user_sequences;
 
INSERT INTO T_AUTOR (CD_AUTOR, NM_PRIMEIRO_NOME_AUTOR, NM_SEGUNDO_NOME_AUTOR,NM_NOME_COMPLETO,DS_EMAIL) 
      VALUES (SQ_AUTOR.nextval , 'RITA DE CASSIA','RODRIGUES','RITA DE CASSIA RODRIGUES','PROFARITA@FIAP.COM.BR');
INSERT INTO T_AUTOR (CD_AUTOR, NM_PRIMEIRO_NOME_AUTOR, NM_SEGUNDO_NOME_AUTOR,NM_NOME_COMPLETO,DS_EMAIL) 
      VALUES (SQ_AUTOR.nextval , 'RITA DE CASSIA2','RODRIGUES2','RITA DE CASSIA RODRIGUES2','PROFARITA2@FIAP.COM.BR');
COMMIT;     

-- SQ_AUTOR.nextval --> NEXTVAL FARÁ COM QUE O PROXIMO VALOR SEQUENCIA SEJA GERADO
-- SQ_AUTOR.CURRVAL --> CURRENT VALUE --> VALOR CORRENTE (ATUAL) DA SEQUENCIA
-- DUAL TABELA DO SISTEMA ORACLE, QUE PODEMOS UTILIZAR PARA CONSULTAR DADOS QUE NÃO ESTÃO ARMAZEMADOS EM TABELA


SELECT * FROM T_AUTOR;

SELECT SQ_AUTOR.CURRVAL FROM DUAL;

SELECT SQ_AUTOR.nextval FROM DUAL;
 
-- EXEMPLO DE GAP - TODAS AS VEZES QUE CHAMAMOS O NEXTVAL, UM NOVO VALOR É GERADO.

