--
ALTER TABLE T_AUTOR_LIVRO
ADD CONSTRAINT CK_AUTOR_LIVRO_STAT
         CHECK (ST_AUTOR_PRINCIPAL IN (1,2));
COMMIT;

--
ALTER TABLE T_LIVRO
ADD CONSTRAINT CK_LIVRO_EDICAO
         CHECK (NR_EDICAO > 0);

ALTER TABLE T_LIVRO
ADD CONSTRAINT CK_LIVRO_ANO
         CHECK (NR_ANO > 0);
COMMIT;

--
ALTER TABLE T_CATEGORIA RENAME COLUMN DS_SIGLA_CATEG TO DS_SIGLA_CATEGORIA;
COMMIT;
--
ALTER TABLE T_CATEGORIA RENAME CONSTRAINT UN_CATEGORIA_CATEGORIA TO UN_CATEGORIA_CATEG;
COMMIT;
--
ALTER TABLE T_AUTOR MODIFY NM_NOME_COMPLETO VARCHAR2(60);
COMMIT;
--
ALTER TABLE T_AUTOR MODIFY DS_EMAIL VARCHAR2(40) NULL;
COMMIT;
--
ALTER TABLE T_LIVRO MODIFY NR_ISBN NUMBER(13);
COMMIT;
--
ALTER TABLE T_AUTOR_LIVRO MODIFY NR_ISBN NUMBER(13);
COMMIT;
--
ALTER TABLE T_AUTOR
ADD nm_pais_origem VARCHAR2(20);
COMMIT;
--
ALTER TABLE T_LIVRO ADD 
CONSTRAINT UN_LIVRO_TITULO
UNIQUE (NM_TITULO);
COMMIT;
--
ALTER TABLE T_AUTOR_LIVRO DROP
CONSTRAINT FK_LIVRO_AUTOR;
COMMIT;
--
ALTER TABLE T_AUTOR DROP
CONSTRAINT PK_AUTOR CASCADE;
COMMIT;
--
ALTER TABLE T_AUTOR DISABLE
CONSTRAINT UN_AUTOR_EMAIL;
COMMIT;
--