--ANTES DO PADRÃO SQL/99
SELECT
  D.CD_DEPTO,
  D.NM_DEPTO,
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO
FROM
  T_SIP_DEPARTAMENTO D,
  T_SIP_FUNCIONARIO F
WHERE
  D.CD_DEPTO = F.CD_DEPTO;
  
-- PADRÃO SQL/99
SELECT
  D.CD_DEPTO,
  D.NM_DEPTO,
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO
FROM
  T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO F
  ON (D.CD_DEPTO = F.CD_DEPTO);
  
--EXEMPLO CONSULTADO 3 TABELAS
SELECT
  P.CD_PROJETO,
  P.NM_PROJETO,
  I.CD_PROJETO,
  I.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I ON (P.CD_PROJETO = I.CD_PROJETO)
  INNER JOIN T_SIP_FUNCIONARIO F ON (I.NR_MATRICULA = F.NR_MATRICULA);
  
-- JUNÇÃO EXTERNA A ESQUERDA --> LEFT OUTER JOIN
-- RECUPERA TODAS AS LINHAS DA TABELA A ESQUERDAQUE SE ASSOCIAM OU NÃO COM AS LINHAS DA TABELA DA DIREITA
-- PADRÃO SQL 99
SELECT
  P.CD_PROJETO,
  P.NM_PROJETO,
  I.CD_PROJETO,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I ON (P.CD_PROJETO = I.CD_PROJETO);
  
-- QUAIS PROJETOS NÃO ESTÃO EM IMPLANTAÇÃO?
SELECT
  P.CD_PROJETO,
  P.NM_PROJETO,
  I.CD_PROJETO,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I ON (P.CD_PROJETO = I.CD_PROJETO)
WHERE
  I.CD_PROJETO IS NULL;

-- JUNÇÃO EXTERNA A DIREITA --> RIGHT OUTER JOIN
-- RECUPERA TODAS AS LINHAS DA TABELA A DIREITA QUE SE ASSOCIAM OU NÃO COM AS LINHAS DA TABELA DA ESQUERDA
-- PADRÃO SQL 99
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.NR_MATRICULA,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F ON (F.NR_MATRICULA = I.NR_MATRICULA);
  
-- QUAIS FUNCIONARIOS NÃO ESTÃO PARTICIPANDO DE IMPLANTAÇÕES?
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.NR_MATRICULA,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F ON (F.NR_MATRICULA = I.NR_MATRICULA)
WHERE
  I.NR_MATRICULA IS NULL;
  
