/*
EXERCICIO 01
LISTE TODOS OS FUNCIONÁRIOS QUE POSSUAM DEPENDENTES. MOSTRE NÚMERO DE MATRÍCULA,
NOME DO FUNCIONÁRIO, NOME DO DEPENDENTE E DATA DE NASCIMENTO DO DEPENDENTE.
MOSTRE O CONTEÚDO ORDENADO POR FUNCIONÁRIO (CRESCENTE) E AINDA EXIBIR OS NOMES DOS
DEPENDENTES EM ORDEM ALFABÉTICA.
UTILIZE APELIDOS PARA AS COLUNAS:
- NÚMERO DE MATRÍCULA ("MATRÍCULA")
- NOME DO FUNCIONÁRIO ("FUNCIONÁRIO")
- NOME DO DEPENDENTE ("NOME DEPENDENTE")
- DATA DE NASCIMENTO DO DEPENDENTE ("DATA NASCIMENTO DEPENDENTE")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABLEAS
- UTILIZE O PADRÃO ORACLE PARA OS COMANDOS
*/
SELECT 
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  D.NM_DEPENDENTE,
  D.DT_NASCIMENTO
FROM
  T_SIP_FUNCIONARIO F,
  T_SIP_DEPENDENTE D 
WHERE 
  F.NR_MATRICULA = D.NR_MATRICULA
ORDER BY F.NR_MATRICULA ASC, D.NM_DEPENDENTE ASC;
-- PADRÃO SQL 99

SELECT 
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  D.NM_DEPENDENTE,
  D.DT_NASCIMENTO
FROM
  T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D ON (F.NR_MATRICULA = D.NR_MATRICULA)
ORDER BY F.NR_MATRICULA ASC, D.NM_DEPENDENTE ASC;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS DEPARTAMENTO,
FUNCIONÁRIO E DEPENDENTE.
LISTE TODOS OS FUNCIONÁRIOS QUE POSSUAM DEPENDENTES. MOSTRE NÚMERO DE MATRÍCULA, NOME DO
FUNCIONÁRIO, NM_DEPARTAMENTO, NOME DO DEPENDENTE E DATA DE NASCIMENTO DO DEPENDENTE.
MOSTRE O CONTEÚDO ORDENADO POR FUNCIONÁRIO (CRESCENTE) E AINDA EXIBIR OS NOMES DOS
DEPENDENTES EM ORDEM ALFABÉTICA.
UTILIZE APELIDOS PARA AS COLUNAS:
- NÚMERO DE MATRÍCULA ("MATRÍCULA")
- NOME DO FUNCIONÁRIO ("FUNCIONÁRIO")
- NOME DO DEPARTAMENTO ("DEPARTAMENTO")
- NOME DO DEPENDENTE ("NOME DEPENDENTE")
- DATA DE NASCIMENTO DO DEPENDENTE ("DATA NASCIMENTO DEPENDENTE")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABLEAS
- UTILIZE O PADRÃO ORACLE PARA OS COMANDOS
*/
SELECT 
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  E.NM_DEPTO,
  D.NM_DEPENDENTE,
  D.DT_NASCIMENTO
FROM
  T_SIP_FUNCIONARIO F,
  T_SIP_DEPENDENTE D,
  T_SIP_DEPARTAMENTO E
WHERE 
F.NR_MATRICULA = D.NR_MATRICULA AND
E.CD_DEPTO = F.CD_DEPTO
ORDER BY F.NR_MATRICULA ASC, D.NM_DEPENDENTE ASC;
--POADRÃO SQL 99
SELECT 
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  E.NM_DEPTO,
  D.NM_DEPENDENTE,
  D.DT_NASCIMENTO
FROM
  T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D ON (F.NR_MATRICULA = D.NR_MATRICULA)
  INNER JOIN T_SIP_DEPARTAMENTO E ON (E.CD_DEPTO = F.CD_DEPTO)
ORDER BY F.NR_MATRICULA ASC, D.NM_DEPENDENTE ASC;
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS PROJETO, IMPLANTAÇÃO E FUNCIONARIO LISTE TODOS OS PROJETOS QUE POSSUAM 
IMPLANTAÇÕES.
MOSTRE O CÓDIGO DO PROJETO, NOME DO PROJETO, DATA DE INÍCIO, CÓDIGO DA IMPLANTACAO,
NOME DO FUNCIONARIO,
DATA DE ENTRADA E DE SAÍDA DO FUNCIONÁRIO DO PROJETO.
MOSTRE O CONTEÚDO ORDENADO POR NOME DO PROJETO (CRESCENTE) E AINDA EXIBIR OS
NOMES DOS FUNCIONÁRIOS PARTICIPANTES DA IMPLANTAÇÃO EM ORDEM ALFABÉTICA.
UTILIZE APELIDOS PARA AS COLUNAS:
- CÓDIGO DO PROJETO ("CD.PROJETO")
- NOME DO PROJETO ("NOME PROJETO")
- DATA DE INÍCIO DA IMPLANTAÇÃO ("INÍCIO")
- CÓDIGO DA IMPLANTAÇÃO ("CD.IMPLANTAÇÃO")
- NOME DO FUNCIONÁRIO ("NOME FUNCIONARIO")
- DATA DA ENTRADA DO FUNCIONÁRIO NO PROJETO ("DATA ENTRADA")
- DATA DA SAÍDA DO FUNCIONÁRIO NO PROJETO ("DATA SAÍDA")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABLEAS
- UTILIZE O PADRÃO ORACLE PARA OS COMANDOS
*/
SELECT
  P.CD_PROJETO,
  P.NM_PROJETO,
  P.DT_INICIO,
  I.CD_IMPLANTACAO,
  F.NM_FUNCIONARIO,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_PROJETO P,
  T_SIP_IMPLANTACAO I,
  T_SIP_FUNCIONARIO F
WHERE
  P.CD_PROJETO = I.CD_PROJETO AND
  I.NR_MATRICULA = F.NR_MATRICULA
ORDER BY P.NM_PROJETO ASC, F.NM_FUNCIONARIO ASC;
  
/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS PROJETO, IMPLANTAÇÃO E FUNCIONARIO
LISTE TODOS OS PROJETOS QUE POSSUAM IMPLANTAÇÕES E QUE AINDA NÃO TENHAM SIDO FINALIZADOS.
MOSTRE O CÓDIGO DO PROJETO, NOME DO PROJETO, DATA DE INÍCIO, CÓDIGO DA IMPLANTACAO,
NOME DO FUNCIONARIO,
DATA DE ENTRADA E DE SAÍDA DO FUNCIONÁRIO DO PROJETO.
MOSTRE O CONTEÚDO ORDENADO POR NOME DO PROJETO (CRESCENTE) E AINDA EXIBIR OS
NOMES DOS FUNCIONÁRIOS PARTICIPANTES DA IMPLANTAÇÃO EM ORDEM ALFABÉTICA.
UTILIZE APELIDOS PARA AS COLUNAS:
UTILIZE APELIDOS PARA AS COLUNAS:
- CÓDIGO DO PROJETO ("CD.PROJETO")
- NOME DO PROJETO ("NOME PROJETO")
- DATA DE INÍCIO DA IMPLANTAÇÃO ("INÍCIO")
- CÓDIGO DA IMPLANTAÇÃO ("CD.IMPLANTAÇÃO")
- NOME DO FUNCIONÁRIO ("NOME FUNCIONARIO")
- DATA DA ENTRADA DO FUNCIONÁRIO NO PROJETO ("DATA ENTRADA")
- DATA DA SAÍDA DO FUNCIONÁRIO NO PROJETO ("DATA SAÍDA")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABLEAS
- UTILIZE O PADRÃO ORACLE PARA OS COMANDOS
*/
SELECT
  P.CD_PROJETO,
  P.NM_PROJETO,
  P.DT_INICIO,
  I.CD_IMPLANTACAO,
  F.NM_FUNCIONARIO,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_PROJETO P,
  T_SIP_IMPLANTACAO I,
  T_SIP_FUNCIONARIO F
WHERE
  P.CD_PROJETO = I.CD_PROJETO AND
  I.NR_MATRICULA = F.NR_MATRICULA AND
  I.DT_SAIDA IS NULL
ORDER BY P.NM_PROJETO ASC, F.NM_FUNCIONARIO ASC;

-- PADRÃO SQL 99

SELECT
  P.CD_PROJETO,
  P.NM_PROJETO,
  P.DT_INICIO,
  I.CD_IMPLANTACAO,
  F.NM_FUNCIONARIO,
  I.DT_ENTRADA,
  I.DT_SAIDA
FROM
  T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I ON (P.CD_PROJETO = I.CD_PROJETO)
  INNER JOIN T_SIP_FUNCIONARIO F ON (I.NR_MATRICULA = F.NR_MATRICULA)
WHERE
  I.DT_SAIDA IS NULL
ORDER BY P.NM_PROJETO ASC, F.NM_FUNCIONARIO ASC;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS FUNCIONÁRIO E
DEPENDENTE.
LISTE TODOS OS FUNCIONÁRIOS QUE NÃO POSSUAM DEPENDENTES (APENAS OS QUE NÃO POSSUEM
DEPENDENTE).
MOSTRE NÚMERO DE MATRÍCULA, NOME DO FUNCIONÁRIO E O NOME DO DEPENDENTE.
MOSTRE O CONTEÚDO ORDENADO POR NOME DO FUNCIONÁRIO (CRESCENTE).
UTILIZE APELIDOS PARA AS COLUNAS:
- NÚMERO DE MATRÍCULA ("MATRÍCULA")
- NOME DO FUNCIONÁRIO ("FUNCIONÁRIO")
- NOME DO DEPENDENTE ("NOME DEPENDENTE")
- DATA DE NASCIMENTO DO DEPENDENTE ("DATA NASCIMENTO DEPENDENTE")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABELAS
- UTILIZE O PADRÃO SQL/99 PARA OS COMANDOS
- UTILIZE LEFT OUTER JOIN
*/
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  D.NM_DEPENDENTE,
  D.DT_NASCIMENTO
FROM
  T_SIP_FUNCIONARIO F LEFT JOIN T_SIP_DEPENDENTE D ON (F.NR_MATRICULA = D.NR_MATRICULA)
WHERE
  D.NR_MATRICULA IS NULL
ORDER BY F.NM_FUNCIONARIO ASC;

/*
PADRÃO ORACLE
*/
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  D.NM_DEPENDENTE,
  D.DT_NASCIMENTO
FROM
  T_SIP_FUNCIONARIO F, 
  T_SIP_DEPENDENTE D
WHERE
  F.NR_MATRICULA = D.NR_MATRICULA (+) AND
  D.NR_MATRICULA IS NULL
ORDER BY F.NM_FUNCIONARIO ASC;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS FUNCIONÁRIO E IMPLANTAÇÃO.
LISTE TODAS AS IMPLANTAÇÕES ASSOCIADAS A FUNCIONÃRIOS (NOTA: NÃO HÁ IMPLANTAÇÃO SEM FUNCIONÁRIO)
MOSTRE NÚMERO DE MATRÍCULA, NOME DO FUNCIONÁRIO, CÓDIGO DA IMPLANTAÇÃO E DATA DE ENTRADA.
MOSTRE O CONTEÚDO ORDENADO POR NOME DO FUNCIONÁRIO E CÓDIGO DA IMPLANTAÇÃO (CRESCENTE).
UTILIZE APELIDOS PARA AS COLUNAS:
- NÚMERO DE MATRÍCULA ("MATRÍCULA")
- NOME DO FUNCIONÁRIO ("FUNCIONÁRIO")
- CÓDIGO DA IMPLANTAÇÃO ("CD. IMPLANTAÇÃO")
- DATA DE ENTRADA ("ENTRADA EM:")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABELAS
- UTILIZE O PADRÃO SQL/99 PARA OS COMANDOS
- UTILIZE RIGHT OUTER JOIN
*/
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.CD_IMPLANTACAO,
  'ENTRADA EM: '|| I.DT_ENTRADA AS DATA_ENTRADA
FROM
  T_SIP_FUNCIONARIO F RIGHT OUTER JOIN T_SIP_IMPLANTACAO I ON (F.NR_MATRICULA = I.NR_MATRICULA)
WHERE
  I.CD_IMPLANTACAO IS NOT NULL
ORDER BY F.NM_FUNCIONARIO, I.CD_IMPLANTACAO;

-- PADRÃO ORACLE
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.CD_IMPLANTACAO,
  'ENTRADA EM: '|| I.DT_ENTRADA AS DATA_ENTRADA
FROM
  T_SIP_FUNCIONARIO F,
  T_SIP_IMPLANTACAO I 
WHERE
  F.NR_MATRICULA(+) = I.NR_MATRICULA AND
    I.CD_IMPLANTACAO IS NOT NULL
ORDER BY F.NM_FUNCIONARIO, I.CD_IMPLANTACAO;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS FUNCIONÁRIO E IMPLANTAÇÃO.
LISTE TODOS OS FUNCIONÁRIOS QUE NÃO PARTICIPAM DE IMPLANTAÇÕES (MOSTRE OS FUNCIONÁRIOS QUE TAMBÉM PARTICIPAM DE IMPLANTAÇÕES).
MOSTRE NÚMERO DE MATRÍCULA, NOME DO FUNCIONÁRIO, CÓDIGO DA IMPLANTAÇÃO E DATA DE ENTRADA.
MOSTRE O CONTEÚDO ORDENADO POR NOME DO FUNCIONÁRIO E CÓDIGO DA IMPLANTAÇÃO (CRESCENTE).
UTILIZE APELIDOS PARA AS COLUNAS:
- NÚMERO DE MATRÍCULA ("MATRÍCULA")
- NOME DO FUNCIONÁRIO ("FUNCIONÁRIO")
- CÓDIGO DA IMPLANTAÇÃO ("CD. IMPLANTAÇÃO")
- DATA DE ENTRADA ("ENTRADA EM:")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABELAS
- UTILIZE O PADRÃO SQL/99 PARA OS COMANDOS
- UTILIZE LEFT OUTER JOIN
*/
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.CD_IMPLANTACAO,
  'ENTRADA EM: '|| I.DT_ENTRADA AS DATA_ENTRADA
FROM
  T_SIP_FUNCIONARIO F LEFT OUTER JOIN T_SIP_IMPLANTACAO I ON (F.NR_MATRICULA = I.NR_MATRICULA)
ORDER BY F.NM_FUNCIONARIO, I.CD_IMPLANTACAO;

-- PADRÃO ORACLE
SELECT
  F.NR_MATRICULA,
  F.NM_FUNCIONARIO,
  I.CD_IMPLANTACAO,
  'ENTRADA EM: '|| I.DT_ENTRADA AS DATA_ENTRADA
FROM
  T_SIP_FUNCIONARIO F,
  T_SIP_IMPLANTACAO I 
WHERE
  F.NR_MATRICULA = I.NR_MATRICULA(+)
ORDER BY F.NM_FUNCIONARIO, I.CD_IMPLANTACAO;

/*
UTILIZE A INSTRUÇÃO SQL PARA REALIZAR A CONSULTA ABAIXO NAS TABELAS FUNCIONÁRIO E
IMPLANTAÇÃO.
LISTE TODOS OS FUNCIONÁRIOS QUE NÃO PARTICIPAM DE IMPLANTAÇÕES (APENAS OS QUE NÃO PARTICIPAM DE
IMPLANTAÇÕES).
MOSTRE NÚMERO DE MATRÍCULA, NOME DO FUNCIONÁRIO, CÓDIGO DA IMPLANTAÇÃO E DATA DE ENTRADA.
MOSTRE O CONTEÚDO ORDENADO POR NOME DO FUNCIONÁRIO E CÓDIGO DA IMPLANTAÇÃO (CRESCENTE).
UTILIZE APELIDOS PARA AS COLUNAS:
- NÚMERO DE MATRÍCULA ("MATRÍCULA")
- NOME DO FUNCIONÁRIO ("FUNCIONÁRIO")
- CÓDIGO DA IMPLANTAÇÃO ("CD. IMPLANTAÇÃO")
- DATA DE ENTRADA ("ENTRADA EM:")
OBSERVAÇÃO:
- UTILIZE APELIDOS E QUALIFICADORES PARA AS TABELAS
- UTILIZE O CONCEITO DE JUNÇÃO DE TABELAS
- UTILIZE O PADRÃO SQL/99 PARA OS COMANDOS
- UTILIZE LEFT OUTER JOIN
*/